=== BackupTheBerlios/infoquiver/InfoQuiver/src/schema/iquiver-data.dtd
<!ELEMENT dataset (
    User|
    Client|
    Address|
    UserGroup|
    UserGroupLnk|
    UserGroupClientLnk|
    Transport|
    TransportAttribute|
    ClientTransportLnk|
    Permission|
    ClientPermissionLnk|
    UserGroupPermissionLnk|
    ContentSourceType|
    ContentSource|
    ContentSourceTransportConfig|
    ContentParser|
    ContentType|
    Content|
    ClientContentLnk)*>
<!ATTLIST dataset
    name CDATA #REQUIRED
>

<!ELEMENT User EMPTY>
<!ATTLIST User
    UserId CDATA #REQUIRED
    UserPassword CDATA #IMPLIED
    UserLogin CDATA #REQUIRED
    UserFirstName CDATA #IMPLIED
    UserMidName CDATA #IMPLIED
    UserLastName CDATA #IMPLIED
    AddressId CDATA #REQUIRED
    ClientId CDATA #REQUIRED
>

<!ELEMENT Client EMPTY>
<!ATTLIST Client
    ClientId CDATA #REQUIRED
    ClientName CDATA #IMPLIED
    AddressId CDATA #REQUIRED
>

<!ELEMENT Address EMPTY>
<!ATTLIST Address
    AddressId CDATA #REQUIRED
    AddressName CDATA #IMPLIED
    AddressStreet CDATA #IMPLIED
    AddressZip CDATA #IMPLIED
    AddressPoBox CDATA #IMPLIED
    AddressPoBoxZip CDATA #IMPLIED
    AddressPhone CDATA #IMPLIED
    AddressMobile CDATA #IMPLIED
    AddressEmail CDATA #IMPLIED
    AddressNumber CDATA #IMPLIED
    AddressCountry CDATA #IMPLIED
>

<!ELEMENT UserGroup EMPTY>
<!ATTLIST UserGroup
    UserGroupId CDATA #REQUIRED
    UserGroupName CDATA #IMPLIED
    UserGroupDesc CDATA #IMPLIED
    ClientId CDATA #REQUIRED
>

<!ELEMENT UserGroupLnk EMPTY>
<!ATTLIST UserGroupLnk
    UserGroupId CDATA #REQUIRED
    UserId CDATA #REQUIRED
>

<!ELEMENT UserGroupClientLnk EMPTY>
<!ATTLIST UserGroupClientLnk
    ClientId CDATA #REQUIRED
    UserGroupId CDATA #REQUIRED
>

<!ELEMENT Transport EMPTY>
<!ATTLIST Transport
    TransportId CDATA #REQUIRED
    TransportName CDATA #REQUIRED
    TransportType CDATA #REQUIRED
    TransportDesc CDATA #IMPLIED
    TransportStartTimeout CDATA #IMPLIED
    TransportImplementation CDATA #REQUIRED
    IsAuthentificationRequired CDATA #IMPLIED
>

<!ELEMENT TransportAttribute EMPTY>
<!ATTLIST TransportAttribute
    TransportAttributeId CDATA #REQUIRED
    TransportId CDATA #REQUIRED
    TransportAttributeName CDATA #REQUIRED
    TransportAttributeType CDATA #REQUIRED
    IsPartOfAuthentification CDATA #IMPLIED
    IsMandatory CDATA #IMPLIED
>

<!ELEMENT ClientTransportLnk EMPTY>
<!ATTLIST ClientTransportLnk
    ClientId CDATA #REQUIRED
    TransportId CDATA #REQUIRED
>

<!ELEMENT Permission EMPTY>
<!ATTLIST Permission
    PermissionId CDATA #REQUIRED
    PermissionName CDATA #IMPLIED
    PermissionDesc CDATA #IMPLIED
>

<!ELEMENT ClientPermissionLnk EMPTY>
<!ATTLIST ClientPermissionLnk
    ClientId CDATA #REQUIRED
    PermissionId CDATA #REQUIRED
>

<!ELEMENT UserGroupPermissionLnk EMPTY>
<!ATTLIST UserGroupPermissionLnk
    UserGroupId CDATA #REQUIRED
    PermissionId CDATA #REQUIRED
    IsNegation CDATA #IMPLIED
>

<!ELEMENT ContentSourceType EMPTY>
<!ATTLIST ContentSourceType
    ContentSourceTypeId CDATA #REQUIRED
    ContentSourceTypeName CDATA #IMPLIED
    ContentSourceTypeDesc CDATA #IMPLIED
>

<!ELEMENT ContentSource EMPTY>
<!ATTLIST ContentSource
    ContentSourceId CDATA #REQUIRED
    ContentSourceTypeId CDATA #REQUIRED
    TransportId CDATA #REQUIRED
    ContentSourceName CDATA #IMPLIED
    ContentSourceDesc CDATA #IMPLIED
    IsAuthentificationRequired CDATA #IMPLIED
>

<!ELEMENT ContentSourceTransportConfig EMPTY>
<!ATTLIST ContentSourceTransportConfig
    ContentSourceId CDATA #REQUIRED
    TransportAttributeId CDATA #REQUIRED
    TransportAttributeValue CDATA #IMPLIED
>

<!ELEMENT ContentParser EMPTY>
<!ATTLIST ContentParser
    ContentParserId CDATA #REQUIRED
    ContentParserImplementation CDATA #REQUIRED
    ContentParserName CDATA #IMPLIED
>

<!ELEMENT ContentType EMPTY>
<!ATTLIST ContentType
    ContentTypeId CDATA #REQUIRED
    ContentTypeName CDATA #REQUIRED
    ContentTypeDesc CDATA #IMPLIED
    ContentParserId CDATA #REQUIRED
>

<!ELEMENT Content EMPTY>
<!ATTLIST Content
    ContentId CDATA #REQUIRED
    ContentTypeId CDATA #REQUIRED
    ContentSourceId CDATA #REQUIRED
    Locale CDATA #IMPLIED
    ReceiveDatetime CDATA #IMPLIED
    ContentContent CDATA #IMPLIED
>

<!ELEMENT ClientContentLnk EMPTY>
<!ATTLIST ClientContentLnk
    ClientId CDATA #REQUIRED
    ContentId CDATA #REQUIRED
    RequestDatetime CDATA #IMPLIED
>

=== BackupTheBerlios/infoquiver/InfoQuiver/src/schema/iquiver-data.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!DOCTYPE dataset SYSTEM "file://iquiver-data.dtd">
<dataset name="all">
    <User UserId="101" UserPassword="root" UserLogin="root" UserFirstName="IQuivers" UserLastName="Root" UserDateOfBirth="2004-07-08 17:58:39.0" AddressId="101" ClientId="101"/>
    <User UserId="102" UserPassword="test" UserLogin="test" UserFirstName="IQuivers" UserLastName="Testuser" UserDateOfBirth="2004-07-08 17:58:43.0" AddressId="102" ClientId="102"/>
    <UserContentSourceLnk UserId="101" ContentSourceId="101"/>
    <UserContentSourceLnk UserId="102" ContentSourceId="101"/>
    <Client ClientId="101" ClientName="ROOT" AddressId="101"/>
    <Client ClientId="102" ClientName="TEST" AddressId="102"/>
    <ClientContentSourceLnk ClientId="101" ContentSourceId="101"/>
    <ClientContentSourceLnk ClientId="102" ContentSourceId="101"/>
    <Address AddressId="101" AddressName="DUMMY ADDRESS FOR ROOT" AddressStreet="None" AddressZip="00000" AddressEmail="netseeker@manskes.de"/>
    <Address AddressId="102" AddressName="TEST" AddressStreet="Demo Square" AddressZip="00001" AddressPhone="+(49)711 123456" AddressEmail="netseeker@manskes.de" AddressNumber="41" AddressCountry="DE"/>
    <UserGroup UserGroupId="101" UserGroupName="ROOT" UserGroupDesc="ROOT" ClientId="101"/>
    <UserGroup UserGroupId="102" UserGroupName="TEST" UserGroupDesc="TEST" ClientId="102"/>
    <UserGroupLnk UserGroupId="101" UserId="101"/>
    <UserGroupLnk UserGroupId="102" UserId="102"/>
    <UserGroupClientLnk ClientId="101" UserGroupId="101"/>
    <UserGroupClientLnk ClientId="102" UserGroupId="102"/>
    <Transport TransportId="101" TransportName="HTTPTransport" TransportType="101" TransportDesc="Simple HTTP Transport" TransportStartTimeout="2004-07-08 17:57:44.0" TransportImplementation="net.sf.iquiver.transport.impl.HTTPTransport"/>
    <TransportAttribute TransportAttributeId="101" TransportId="101" TransportAttributeName="Server" TransportAttributeType="" IsPartOfAuthentification="0" IsMandatory="1"/>
    <TransportAttribute TransportAttributeId="102" TransportId="101" TransportAttributeName="Port" TransportAttributeType="" IsPartOfAuthentification="0" IsMandatory="0"/>
    <TransportAttribute TransportAttributeId="103" TransportId="101" TransportAttributeName="Login" TransportAttributeType="" IsPartOfAuthentification="1" IsMandatory="0"/>
    <TransportAttribute TransportAttributeId="104" TransportId="101" TransportAttributeName="Password" TransportAttributeType="" IsPartOfAuthentification="1" IsMandatory="0"/>
    <Permission PermissionId="101" PermissionName=""/>
    <ContentSourceType ContentSourceTypeId="101" ContentSourceTypeName="Internet"/>
    <ContentSourceTypeTransportLnk ContentSourceTypeId="101" TransportId="101"/>
    <ContentSource ContentSourceId="101" ContentSourceTypeId="101" TransportId="101" ContentSourceName="HTML Test Content Source" ContentSourceDesc="HTML Test Content Source" IsAuthentificationRequired="0"/>
    <ContentSourceTransportConfig ContentSourceId="101" TransportAttributeId="101" TransportAttributeValue="http://www.manskes.de"/>
    <ContentParser ContentParserId="101" ContentParserImplementation="net.sf.iquiver.parser.impl.TextParser" ContentParserName="Text Parser"/>
    <ContentParser ContentParserId="102" ContentParserImplementation="net.sf.iquiver.parser.impl.HtmlParser" ContentParserName="HTML Parser"/>
    <ContentType ContentTypeId="101" ContentTypeName="text/plain" ContentTypeDesc="Plain Text" ContentParserId="0"/>
    <ContentType ContentTypeId="102" ContentTypeName="text/html" ContentTypeDesc="HTML" ContentParserId="1"/>
</dataset>
